openapi: 3.0.0
info:
  title: One Social
  description: Manage all your social media platforms from one single web app
  version: 1.0.0

servers:
  - url: http://localhost:5000/api/v1/
    description: localhost base route
  - url: http://localhost:5000/api/v1/dummy
    description: Get dummy info

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /instagram:
    get:
      summary: Returns user details like username, followers, follows, etc.
      description: Optional extended description
      responses:
        '200':
          description: An object of user details
          content:
            application/json:
              schema: 
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: string
                  follows:
                    type: string
                  date:
                    type: string
    post:
      summary: sends username.
      description: Optional extended description
      responses:
        '200':
          description: A username
          content:
            application/json:
              schema: 
                type: object
                properties:
                  username:
                    type: string
  /facebook:
    get:
      summary: Returns user details like username, followers, follows, etc.
      responses:
        '200':
          description: An object of user details
          content:
            application/json:
              schema: 
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: string
                  follows:
                    type: string
                  date:
                    type: string
  /{token}:
    get:
      summary: Returns params.
      parameters:
        - name: token
          default: 5
          in: path
      responses:
        '200':
          description: An object of params with it's token
          content:
            application/json:
              schema: 
                type: object
                properties:
                  token:
                    type: string
